name: CloudCore
version: 1.0.0
main: systems.mythical.cloudcore.spigot.CloudCoreSpigot
author: Mythical
description: A simple MySQL connection plugin
softdepend:
  - LuckPerms
  - Vault
  - Essentials
  - PlaceholderAPI
  - ASkyBlock
  - Jobs
  - BedWars1058
  - Votifier
commands:
  spigotconsole:
    description: Execute a command as the server console (Spigot).
    usage: /spigotconsole <command>
    aliases: [scex, cex]
  scex:
    description: Alias for /spigotconsole
    usage: /scex <command>
  cex:
    description: Alias for /spigotconsole
    usage: /cex <command>