# Server Configuration
server:
  port: 9882
  host: "0.0.0.0"

# WebSocket Configuration
websocket:
  path: "/ws"
  maxFrameSize: 65536
  connection:
    uri: "ws://localhost:9882/ws"
    reconnectInterval: 5000
    maxReconnectAttempts: 5
    timeout: 30000

# Authentication Configuration
auth:
  jwtSecret: "yes"

# Logging Configuration
logging:
  level: "INFO"
  file: "logs/mccloudadmin-server.log"

# Database Configuration
database:
  url: "jdbc:mysql://localhost:3306/mccloudadmin"
  username: "mythical"
  password: ""
  maxPoolSize: 20
  minIdle: 10
  idleTimeout: 60000
  connectionTimeout: 5000 